apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - image: petreskiv/frontend:0.5
          name: frontend
          ports:
            - containerPort: 80
              name: server
              protocol: TCP
---

apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
      targetPort: server
  loadBalancerIP: "34.118.27.83"
  selector:
    app: frontend