FROM pytorch/pytorch:latest

WORKDIR /app

COPY ./docker-ready/pos /app/

RUN pip install -r ./requirements-pos.txt

# Install additional requirements to run REST API
#RUN pip install -r requirements-api.txt

EXPOSE 5030

CMD ["uvicorn", "pos:app", "--host", "0.0.0.0", "--port", "5030"]