FROM python:3.9

WORKDIR /app

COPY ./docker-ready/coref/ /app/

RUN pip install -r ./requirements.txt

# Install additional requirements to run REST API
#RUN pip install -r requirements-api.txt

EXPOSE 5020

CMD ["uvicorn", "coref:app", "--host", "0.0.0.0", "--port", "5020"]