version: '3.9'

services:
  ner:
    image: ner
    ports:
      - "5040:5040"

  pos:
    image: pos
    environment:
      POS_MODEL_PATH: "/app/models/sloberta"
    ports:
      - "5030:5030"

  coref:
    image: coref
    environment:
      COREF_MODEL_PATH: "/app/models/sloberta"
    ports:
      - "5020:5020"

  pipeline:
    image: pipeline
    environment:
      SLO_COREF_SERVICE_HOST: "coref"
      SLO_COREF_SERVICE_PORT: "5020"
      SLO_NER_SERVICE_HOST: "ner"
      SLO_NER_SERVICE_PORT: "5040"
      SLO_POS_SERVICE_HOST: "pos"
      SLO_POS_SERVICE_PORT: "5030"
      CLASSLA_RESOURCES_DIR: "/app/data/classla"
    ports:
      - "5050:5050"
    links:
      - ner
      - pos
      - coref
  frontend:
    image: frontend
    ports:
      - "8080:80"
    links:
      - pipeline